modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="modulargolems"
version="${file.jarVersion}" #mandatory
displayName="Modular Golems" #mandatory
logoFile="modulargolems.png" #optional
credits="LightLand team and Nulladev Team" #optional
authors="lcy0x1" #optional
description='''
This mod adds golems that can be crafted with different materials in a Tinker-like playstyle.
'''
[[dependencies.modulargolems]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.18,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="curios"
    mandatory=false
    versionRange="[5.3.4,)"
    side="BOTH"